name: Generate SBOM
on:
 push:
  branches: ["main"]

permissions:
 actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Generate SBOM with Syft
      run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft . -o spdx=sbom.json

    - name: Commit SBOM
      run: |
          git config --global user.email "palsagnik2102@gmail.com"
          git config --global user.name  "SAGNIK PAL"
          git add sbom.json
          git commit -m "Add SBOM" -a --allow-empty
          git push --all
