name: Generate SBOM
on:
 push:
  branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Generate SBOM
      run: |
          syft packages . -o ./sbom.json
    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v4
      with:
       name: sbom
       path: sbom.json
