name: Generate SBOM
on:
 push:
  branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Generate SBOM with Syft
      run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft packages -f spdx -o sbom.spdx.json .
          # Optional:  Verify SBOM (example)
          # syft packages -f spdx -o sbom.spdx.json . | jq .

    - name: Commit SBOM
      run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git add sbom.spdx.json
          git commit -m "Add SBOM" -a --allow-empty
          git push --all
