name: Vulnerability Report Generation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Grype scan
        uses: anchore/scan-action@v3
        id: grype-scan
        with:
          path: "./"
          fail-build: false
          severity-cutoff: "medium"
          output-format: "sarif"
          output-file: "grype-report.sarif"  # Explicit filename

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype-report.sarif  # Direct file reference

      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: grype-report.sarif
