name: Vulnerability Report Generation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Grype scan
        id: grype_scan
        uses: anchore/scan-action@v3
        with:
          path: "./"
          fail-build: false
          output-format: "json"  # or "sarif" if you want SARIF

      - name: Show Grype report path
        run: echo "Grype report path is ${{ steps.grype_scan.outputs.report }}"
      
      - name: Upload Grype report artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-vulnerability-report
          path: ${{ steps.grype_scan.outputs.report }}
